language: java
sudo: required
jdk:
  - openjdk11
before_script:
  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  - unzip gradle-6.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.5
  - export PATH=$GRADLE_HOME/bin:$PATH
addons:
  sonarcloud:
    organization: "carledriss-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
    - develop
script:
- gradle compileJava compileTestJava
- sonar-scanner
- gradle check
notifications:
  email: true
